### ISSUE TITLE
Nesting BEM-ing

### ISSUE THREAD

**Issue by alan-agius4** [davidtheclark/stylelint-statement-max-nesting-depth#10]
Came across one thing which maybe can be added as improvements or enhancements 

```
  .selections {
     &-row {
        width: 500px;
        padding: 5px;

        & > div {
             background: blue;

           &:nth-child(1) {
              background: yellow;
           }
        }
      }
   }
```

If my nesting limit is set to 3, I will have get the warning "Nesting exceeds maximum nesting depth".
As the `&-row` is counted as another nesting level. As this nesting level is not visible in CSS as it is compiled down `selections-row > div:nth-child(1)` It would be nice to have an option to not count SASS BEM-ing,

**Comment by davidtheclark** [comment]
PR welcome. Seems like a fine option to me. Would need to come up with an option name and implementation that isn't Sass-specific (works with Less and PostCSS nesting plugins).

**Comment by alan-agius4** [comment]
Not to do breaking changes the default can be set to `true`
Not sure, maybe: `CountParentSelectorsPrefixAmpersand`

**Comment by jeddy3** [comment]
Deprecated.

**Comment by robsterlini** [comment]
Long shot here, but was this ever implemented in https://github.com/stylelint/stylelint/tree/master/lib/rules/max-nesting-depth? It would be so good to have it there!

**Comment by H-L** [comment]
If you don't want stylelint to count the many depth created by composing BEM classes with ampersand, [selector-max-compound-selectors](https://stylelint.io/user-guide/rules/selector-max-compound-selectors) might be a better alternative as it does only count **compiled depth**.

```scss
// SCSS Nested classname
.block {
  &__element { /* ignored */
    &--modifier { /* ignored */
      .subclass { /* 1 */
        
      }
    }
  }
}

// Result
.block__element--modifier .subclass {} /* Result only have 1 depth level */
```
