### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/stylelint-statement-max-nesting-depth#11]
As of stylelint 4.5, people should use http://stylelint.io/user-guide/rules/max-nesting-depth/

**Comment by jeddy3** [comment]
@davidtheclark Do you want to grant me access to this repo, so I can deprecate?

**Comment by davidtheclark** [comment]
Sorry, slipped me mind.

**Comment by jeddy3** [comment]
Oops, I need npm access too to do the deprecation...

**Comment by davidtheclark** [comment]
Deprecated.
