### ISSUE TITLE
Update dependency of stylelint?

### ISSUE THREAD

**Issue by onlywei** [davidtheclark/stylelint-statement-max-nesting-depth#7]
Right now, this rule will double-install `stylelint` version 3 when using `stylelint` version 4 into `node_modules`. Should the dependency in `package.json` be updated?

**Comment by davidtheclark** [comment]
Yes. It should allow a range from 3+, I guess. Will take care of this tonight.

**Comment by davidtheclark** [comment]
Published in 2.0.1.
